name: Update Version and Publish Zip to GitHub Packages

on:
  push:
    tags:
      - "*"

jobs:
  update-version-and-publish-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update Version in Manifest
        run: |
          version="${{ env.TAG_NAME }}"
          jq --arg new_version "$version" '.version = $new_version' manifest.json > manifest.tmp && mv manifest.tmp manifest.json

      - name: Set Filename Variable
        id: set_filename
        run: echo "FILENAME=twitch-points-auto-collector_${{ env.TAG_NAME }}.zip" >> $GITHUB_ENV

      - name: Create Zip Archive
        run: |
          zip -r "$FILENAME" *
          echo "$FILENAME created"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: Auto-generated release for version ${{ env.TAG_NAME }}

      - name: Upload Zip to Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "${{ env.FILENAME }}"
          asset_name: "${{ env.FILENAME }}"
          asset_content_type: application/zip

      - name: Switch to Master Branch
        run: |
          git checkout master

      - name: Commit Changes
        run: |
          git add manifest.json
          git commit -m "Update version and add release asset"
          git push origin master

      - name: Cleanup
        run: rm "$FILENAME"