name: Update Version and Publish Zip to GitHub Packages

on:
  create:
    tags:
      - "v*"

jobs:
  update-version-and-publish-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Name
        id: extract_tag
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Update Version in Manifest
        run: |
          tag="${{ steps.extract_tag.outputs.TAG_NAME }}"
          version="${tag#v}"
          sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/\"version\": \"$version\"/" manifest.json

      - name: Create Zip Archive
        run: |
          zip -r twitch-points-auto-collector.zip *

      - name: Authenticate npm with GitHub Token
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Zip to GitHub Packages
        run: npm publish twitch-points-auto-collector.zip --access public --registry https://npm.pkg.github.com

      - name: Cleanup
        run: rm twitch-points-auto-collector.zip
