name: Update Version and Publish Zip to GitHub Packages

on:
  create:
    tags:
      - "v*"

jobs:
  update-version-and-publish-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Name
        id: extract_tag
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Update Version in Manifest
        run: |
          tag="${{ steps.extract_tag.outputs.TAG_NAME }}"
          version="${tag#v}"
          jq --arg new_version "$version" '.version = $new_version' manifest.json > manifest.tmp && mv manifest.tmp manifest.json


      - name: Create Zip Archive
        run: |
          zip -r twitch-points-auto-collector.zip *

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.TAG_NAME }}
          release_name: Release ${{ steps.extract_tag.outputs.TAG_NAME }}
          body: Auto-generated release for version ${{ steps.extract_tag.outputs.TAG_NAME }}

      - name: Upload Zip to Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: twitch-points-auto-collector.zip
          asset_name: twitch-points-auto-collector.zip
          asset_content_type: application/zip

      - name: Set Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add manifest.json
          git commit -m "Update version and add release asset"
          git push

      - name: Cleanup
        run: rm twitch-points-auto-collector.zip
